V0.0.2 get unspent rpc
NAVCoin/polymorph pull request #220
Opened 2018-03-28 23:17 UTC by matt-auckland

2018-03-28 23:43 UTC, ro-savage requested changes
I am not sure the purpose of this PR?
Why do we need to write a wrapper around `rpc.listUnspent()` ?

2018-03-28 23:43 UTC, ro-savage commented on server/src/lib/rpc/client.js
> +rpc.nav.listUnspentTx = async () => {
Why do we need this?
Can't we just use `rpc.listUnspent()` directly? Why does it need a wrapper?

2018-03-28 23:43 UTC, ro-savage commented on server/test/lib.rpc.client.spec.js
> +  describe('(nav.listUnspentTx)', () => {
If we don't have a wrapper, we don't need this test.

2018-03-29 00:20 UTC, matt-auckland commented
actually you're right 🤦‍♂️ 
I'm closing this.

2018-03-29 00:20 UTC, closed without merging